// // // import "./public/libs/jquery.magnific-popup.min";
// import "./public/libs/jquery-min";
// import "./public/libs/popper.min";
// // import "./public/libs/classie";
// import "./public/libs/bootstrap.min";
// // import "./public/libs/nivo-lightbox";
// // import "./public/libs/owl.carousel";
// // import "./public/libs/jquery.stellar.min";
// // import "./public/libs/jquery.nav";
// // import "./public/libs/scrolling-nav";
// // import "./public/libs/jquery.mixitup";
// // import "./public/libs/jquery.counterup.min";
// // // import "./public/libs/jquery.easing.min";
// // import "./public/libs/wow";
// // import "./public/libs/main";
import "jquery/dist/jquery";
import "popper.js/dist/popper";
